Attribute VB_Name = "m_Test_Autogenerated_DB_Classes"
Option Compare Database

'' Tests for the cDB_Settings class.
'' Each function tests a specific method or property within the class.
'' Functions return True if the test passes, and False otherwise.

Function Test_cDB_Setting_id() As Boolean
    '' Tests if the correct ID is returned for a setting with the name 'Test_Setting'.
    On Error GoTo ErrorHandler
    Dim Settings As New cDB_Settings
    Test_cDB_Setting_id = Settings.id(filter:="Name LIKE 'Test_Setting'") = 1
    Exit Function

ErrorHandler:
    Debug.Print "Error in Test_cDB_Setting_id: " & err.Description
    Test_cDB_Setting_id = False
End Function

Function Test_ParameterPValue() As Boolean
    '' Tests if the correct PValue is returned for a setting with the name 'Test_Setting'.
    On Error GoTo ErrorHandler
    Dim Settings As New cDB_Settings
    Test_ParameterPValue = Settings.PValue("Test_Setting") = "Test1"
    Exit Function

ErrorHandler:
    Debug.Print "Error in Test_ParameterPValue: " & err.Description
    Test_ParameterPValue = False
End Function

Function Test_ParameterPBoolean() As Boolean
    '' Tests if the correct PBoolean is returned for a setting with the name 'Test_Setting'.
    On Error GoTo ErrorHandler
    Dim Settings As New cDB_Settings
    Test_ParameterPBoolean = Settings.PBoolean("Test_Setting") = True
    Exit Function

ErrorHandler:
    Debug.Print "Error in Test_ParameterPBoolean: " & err.Description
    Test_ParameterPBoolean = False
End Function

