version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  user:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: data/log/user.log
    mode: w
  debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: data/log/debug.log
    mode: w

loggers:
  user_logger:
    level: DEBUG
    handlers: [user]
    propagate: yes
  debug_logger:
    level: DEBUG
    handlers: [debug]
    propagate: yes

root:
  level: DEBUG
  handlers: [console]
